name: cyberme_flutter
description: CyberMe Flutter Interface

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  sprintf: ^6.0.0
  shared_preferences: ^2.0.13
  rive: ^0.8.4
  provider: ^6.0.2
  url_launcher: ^6.1.0
  image_picker: ^0.8.5
  flutter_image_compress: ^1.1.0
  clipboard: ^0.1.3
  quick_actions: ^0.6.0+10
  intl: ^0.18.0
  dio: ^4.0.6
  swipable_stack: ^1.3.0
  crypto: ^3.0.2
  json_annotation: ^4.8.1
  health: ^8.0.0 #https://pub.dev/packages/health/example

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/dash/
    - images/health/
#  module:
#    androidX: true
#    androidPackage: com.mazhangjing.cyberme-flutter
#    iosBundleIdentifier: com.mazhangjing.cyberme-flutter
