name: cyberme_flutter
description: CyberMe Flutter Interface

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.4"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.16.0
  google_fonts: ^6.1.0
  http: ^1.0.0
  pointycastle: ^3.7.0
  flutter_curve25519: ^0.1.2
  sprintf: ^6.0.0
  url_launcher: ^6.1.0
  image_picker: ^0.8.5
  flutter_image_compress: ^1.1.0
  clipboard: ^0.1.3
  quick_actions: ^0.6.0+10
  intl: ^0.18.0
  uuid: ^3.0.6
  dio: ^5.0.0
  swipable_stack: ^1.3.0
  crypto: ^3.0.2
  json_annotation: ^4.8.1
  flutter_inappwebview: ^5.8.0
  cached_network_image: ^3.3.0
  health_kit_reporter: ^2.1.1
  hooks_riverpod: ^2.4.6
  flutter_hooks: ^0.20.3
  riverpod_annotation: ^2.3.1
  freezed_annotation: ^2.4.1
  table_calendar: ^3.0.9
  window_manager: ^0.3.7
  system_tray: ^2.0.3
  pasteboard: ^0.2.0
  flutter_animate: ^4.4.0
  flutter_map: ^6.1.0
  characters: ^1.3.0
  flame_forge2d: ^0.18.0
  qr_flutter: ^4.0.0
  xml: ^6.5.0
  equatable: ^2.0.5
  sticky_grouped_list: ^3.1.0
  flutter_widget_from_html: ^0.15.1
  html: ^0.15.4
  json_pretty: ^1.0.4
  flutter_markdown: ^0.7.3
  shared_preferences: ^2.3.1
  flutter_screen_lock: ^9.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.6
  freezed: ^2.4.5
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.4

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/dash/
    - images/health/
    - images/tray/
    - images/angrybirds/
  fonts:
   - family: Sank
     fonts:
       - asset: fonts/sank.ttf
  module:
# #    androidX: true
# #    androidPackage: com.mazhangjing.cyberme-flutter
    iosBundleIdentifier: com.mazhangjing.landmark
